const FUNCTION_URL='https://mcebteebdfnrksnrokvt.supabase.co/functions/v1/enviar-pre-cadastro';
const $=s=>document.querySelector(s);let step=0;const data={};
const steps=[
{title:'Dados pessoais',sub:'Vamos começar com seus dados.',html:`${f('nome_completo','Nome completo')}${f('cpf','CPF','text','000.000.000-00')}<div class="grid2">${f('data_nascimento','Data de nascimento','date')}${sel('estado_civil','Estado civil',['Solteiro(a)','Casado(a)','União estável','Divorciado(a)','Viúvo(a)'])}</div>${f('whatsapp','WhatsApp','tel','(99) 99999-9999')}`},
{title:'Endereço',sub:'Informe onde você mora.',html:`${f('cep','CEP','text','00000-000')}${f('rua','Rua / Avenida')}<div class="grid2">${f('numero','Número')}${f('complemento','Complemento','text','Opcional')}</div>${f('bairro','Bairro')}<div class="grid2">${f('cidade','Cidade')}${f('estado','Estado','text','MA')}</div>`},
{title:'Trabalho e renda',sub:'Conte um pouco sobre sua atividade profissional.',html:`${f('profissao','Profissão')}${f('empresa_trabalho','Empresa / local de trabalho')}${f('renda_mensal','Renda mensal','number','R$')}`},
{title:'Referência pessoal',sub:'Informe uma pessoa que possamos contatar.',html:`${f('referencia_nome','Nome da referência')}${f('referencia_telefone','Telefone da referência','tel')}${f('referencia_relacao','Relação / parentesco')}`},
{title:'Documento',sub:'Escolha RG ou CNH.',html:`${sel('tipo_documento','Tipo de documento',['RG','CNH'])}<div class="field"><label>Foto da frente</label><input required type="file" id="documento_frente" accept="image/jpeg,image/png,image/webp,application/pdf"></div><div class="field" id="versoField"><label>Foto do verso</label><input type="file" id="documento_verso" accept="image/jpeg,image/png,image/webp,application/pdf"></div>`},
{title:'Comprovantes',sub:'Últimos documentos para finalizar.',html:`<div class="field"><label>Comprovante de endereço</label><input required type="file" id="comprovante_endereco" accept="image/jpeg,image/png,image/webp,application/pdf"></div><div class="field"><label>Selfie</label><input required type="file" id="selfie" accept="image/jpeg,image/png,image/webp"></div>`},
{title:'Autorização',sub:'Confira e autorize a análise.',html:`<div class="check"><input id="autorizado_analise" type="checkbox" required><label for="autorizado_analise">Autorizo a Loja Maranhão a analisar os dados enviados neste pré-cadastro para avaliação do crediário.</label></div><p class="subtitle" style="margin-top:18px">Ao enviar, você declara que as informações fornecidas são verdadeiras.</p>`}
];
function f(id,label,type='text',ph=''){return `<div class="field"><label for="${id}">${label}</label><input id="${id}" name="${id}" type="${type}" placeholder="${ph}" ${id==='complemento'?'':'required'}></div>`}function sel(id,label,opts){return `<div class="field"><label for="${id}">${label}</label><select id="${id}" name="${id}" required><option value="">Selecione</option>${opts.map(x=>`<option>${x}</option>`).join('')}</select></div>`}
$('#startBtn').onclick=()=>{$('#cover').classList.add('hidden');$('#formScreen').classList.remove('hidden');render()};
$('#backBtn').onclick=()=>{save();if(step===0){$('#formScreen').classList.add('hidden');$('#cover').classList.remove('hidden')}else{step--;render()}};
$('#nextBtn').onclick=async()=>{if(!validate())return;save();if(step<steps.length-1){step++;render()}else await submit()};
function render(){const s=steps[step];$('#stepContent').innerHTML=`<div class="card"><h2>${s.title}</h2><p class="subtitle">${s.sub}</p>${s.html}</div>`;$('#stepLabel').textContent=`${step+1} de ${steps.length}`;$('#progressBar').style.width=`${((step+1)/steps.length)*100}%`;$('#nextBtn').textContent=step===steps.length-1?'ENVIAR PRÉ-CADASTRO':'Continuar';Object.entries(data).forEach(([k,v])=>{const e=document.getElementById(k);if(e&&e.type!=='file'&&e.type!=='checkbox')e.value=v});if(step===4){const t=$('#tipo_documento');const sync=()=>{$('#versoField').style.display=t.value==='CNH'?'none':'grid'};t.onchange=sync;sync()}}
function validate(){const els=[...$('#stepContent').querySelectorAll('input,select')];for(const e of els){if(e.id==='documento_verso'&&$('#tipo_documento')?.value==='CNH')continue;if(!e.checkValidity()){e.reportValidity();return false}}return true}
function save(){[...$('#stepContent').querySelectorAll('input,select')].forEach(e=>{if(e.type!=='file'&&e.type!=='checkbox')data[e.id]=e.value})}
async function file64(id){const el=document.getElementById(id);const file=el?.files?.[0];if(!file)return null;if(file.size>5*1024*1024)throw new Error('Cada arquivo deve ter no máximo 5 MB.');return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res({base64:r.result,nome:file.name,tipo:file.type});r.onerror=rej;r.readAsDataURL(file)})}
async function submit(){const btn=$('#nextBtn');btn.disabled=true;btn.textContent='Enviando...';try{const payload={...data,consentimento:true,autorizado_analise:true,arquivos:{documento_frente:await file64('documento_frente'),documento_verso:await file64('documento_verso'),comprovante_endereco:await file64('comprovante_endereco'),selfie:await file64('selfie')}};const r=await fetch(FUNCTION_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const out=await r.json();if(!r.ok)throw new Error(out.error||out.message||'Não foi possível enviar o pré-cadastro.');$('#protocol').textContent=out.protocolo;$('#formScreen').classList.add('hidden');$('#successScreen').classList.remove('hidden')}catch(e){alert(e.message||'Erro ao enviar. Tente novamente.');btn.disabled=false;btn.textContent='ENVIAR PRÉ-CADASTRO'}}
