function whatsappUrl(numero){let d=String(numero||'').replace(/\D/g,'');if(d.length===10||d.length===11)d='55'+d;return d?`https://wa.me/${d}`:''}
function whatsappUrlComTexto(numero,texto){const base=whatsappUrl(numero);return base?`${base}?text=${encodeURIComponent(texto)}`:''}
async function downloadDocument(path,label){try{const {data,error}=await db.storage.from('pre_cadastros_documentos').createSignedUrl(path,300);if(error||!data?.signedUrl)throw new Error('Não foi possível gerar o link do documento.');const r=await fetch(data.signedUrl);if(!r.ok)throw new Error('Não foi possível baixar o documento.');const blob=await r.blob();const ext=(String(path).split('.').pop()||'arquivo').replace(/[^a-z0-9]/gi,'');const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${String(current?.protocolo||'cliente')}-${String(label||'documento').toLowerCase().replace(/[^a-z0-9]+/gi,'-')}.${ext}`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}catch(e){alert(e.message||'Não foi possível baixar o documento.')}}
function mensagemAprovacao(cliente,limite){const nome=String(cliente?.nome_completo||'cliente').trim().split(/\s+/)[0]||'cliente';const valor=Number(limite||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});return `🎉 Olá, ${nome}! Seu pré-cadastro na Maranhão foi APROVADO.\n\n💳 Limite aprovado: ${valor}\n\nPara finalizar seu cadastro, continue o atendimento por aqui no WhatsApp ou dirija-se à nossa loja:\n📍 Rua São Paulo do Norte, nº 40 – Centro, Grajaú/MA\n\nLeve seu protocolo e seus documentos.\n\nProtocolo: ${cliente?.protocolo||'—'}\n\nMaranhão Calçados`;}
async function aprovarEabrirWhatsApp(){const limite=$('#editLimit').value===''?null:Number($('#editLimit').value);if(!limite||limite<=0)return alert('Informe um limite aprovado maior que zero.');const clienteAtual=current;const popup=window.open('about:blank','_blank');const {error}=await db.from('pre_cadastros').update({status:'aprovado',limite_aprovado:limite,responsavel:$('#editResponsible').value.trim()||null,observacoes:$('#editNotes').value.trim()||null}).eq('id',clienteAtual.id);if(error){if(popup)popup.close();return alert('Não foi possível salvar a análise.');}const url=whatsappUrlComTexto(clienteAtual.whatsapp,mensagemAprovacao(clienteAtual,limite));alert('Cliente aprovado com sucesso! Vou abrir o WhatsApp com a mensagem pronta.');$('#detailDialog').close();await loadClients();if(url){if(popup)popup.location.href=url;else window.open(url,'_blank','noopener');}else if(popup)popup.close();}
function enhanceClientDetail(){if(!current)return;const wa=whatsappUrl(current.whatsapp);const wa2=whatsappUrl(current.whatsapp_secundario);document.querySelectorAll('#detailBody .kv').forEach(row=>{const spans=row.querySelectorAll('span');if(spans.length<2)return;if(spans[0].textContent.trim()==='WhatsApp'&&wa){spans[0].textContent='WhatsApp 1';spans[1].innerHTML=`<a href="${wa}" target="_blank" rel="noopener" style="display:inline-flex;align-items:center;gap:6px;font-weight:700;text-decoration:none">💬 ${esc(current.whatsapp)} <small>Abrir WhatsApp</small></a>`;if(current.whatsapp_secundario&&!document.getElementById('whatsappSecundarioRow')){const second=document.createElement('div');second.className='kv';second.id='whatsappSecundarioRow';second.innerHTML=`<span>WhatsApp 2</span><span><a href="${wa2}" target="_blank" rel="noopener" style="display:inline-flex;align-items:center;gap:6px;font-weight:700;text-decoration:none">💬 ${esc(current.whatsapp_secundario)} <small>Abrir WhatsApp</small></a></span>`;row.after(second);}}});
 document.querySelectorAll('#detailBody .doc-btn').forEach(btn=>{if(btn.dataset.downloadReady==='1')return;btn.dataset.downloadReady='1';const wrap=document.createElement('div');wrap.style.display='flex';wrap.style.gap='8px';wrap.style.flexWrap='wrap';btn.parentNode.insertBefore(wrap,btn);wrap.appendChild(btn);const dl=document.createElement('button');dl.type='button';dl.className='open-btn';dl.textContent='⬇ BAIXAR';dl.style.minWidth='110px';dl.onclick=e=>{e.stopPropagation();downloadDocument(btn.dataset.path,btn.textContent)};wrap.appendChild(dl);});
 const aprovar=document.querySelector('#approveAnalysis');if(aprovar)aprovar.onclick=aprovarEabrirWhatsApp;
}
const originalOpenClient=openClient;openClient=async function(id){await originalOpenClient(id);enhanceClientDetail();};